all: update

create:
	menhir --list-errors --infer src/syntax/parser.mly > haxe.messages

update:
	cp haxe.messages haxe.messages.backup
	menhir --update-errors haxe.messages.backup --infer src/syntax/parser.mly > haxe.messages
	menhir --compile-errors haxe.messages --infer src/syntax/parser.mly > src/syntax/syntaxErrors.ml